### ISSUE TITLE
Possible to expose method that returns string?

### ISSUE THREAD

**Issue by dbashford** [SheetJS/js-ppt#2]
I see you are `console.log`ing all the output.  It would be nice if there was a way to call, for instance, `readFile` (or a new function) directly and get a string back and save the trouble of using a child process.

**Comment by SheetJSDev** [comment]
The console.log was a stopgap measure since I didn't have a good sense for what the presentation object structure looks like.  The next iteration will return an object, and there will be a helper function to get an array of strings

**Comment by SheetJSDev** [comment]
@dbashford see https://github.com/SheetJS/js-ppt/blob/master/bin/ppt.njs#L12-L13 for usage.  readFile returns an object, and PPT.utils.to_text produces an array of strings.
